name: Link Check Deploy
on:
  check_run:
    types: [completed]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - id: build_check
        uses: LouisBrunner/checks-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Report
          status: queued

      - name: Run Link Check
        id: run_check
        uses: "iterative/link-check.action@master"
        with:
          configFile: "config/link-check/config.yml"
          rootURL: "${{ github.event.deployment.payload.web_url }}"
          output: checksAction

      - uses: LouisBrunner/checks-action@v1.0.0
        if: ${{ success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.build_check.outputs.check_id }}
          status: completed
          conclusion: ${{ steps.build_check.outputs.conclusion }}
          output: ${{ steps.build_check.outputs.output }}

      - uses: LouisBrunner/checks-action@v1.0.0
        if: ${{ failure() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.build_check.outputs.check_id }}
          status: completed
          conclusion: failure
          output: >-
            {"summary": "The Link Check script had an error!"}
